CREATE TABLE IF NOT EXISTS st_data (
`id` int NOT NULL AUTO_INCREMENT,
`symbol` varchar(255), 
`exchange` varchar(255), 
`name` varchar(255), 
`change` float, 
`close` float, 
`percentageChange` float, 
`open` float, 
`high` float, 
`low` float, 
`volume` float, 
`avgVolume` float, 
`high52` float, 
`low52` float, 
`marketCap` float, 
`eps` float, 
`shares` float, 
`time` int, 
`day` int, 
`month` int, 
`year` int,
PRIMARY KEY (`id`)
);
